"""`.env.example`, rendered from the settings model.

The decisions log claimed for a while that this file "is generated from the model
itself so the two cannot drift". It was not, and it had: forty fields on the model,
thirty-six in the file, with `FLOODLINE_DATABASE_URL` - the one setting a deployment
most needs - among the missing. A documented safeguard that does not exist is worse
than none, because it is trusted.

So the claim is now true. Every `FLOODLINE_` line below comes from a field: its name,
its description and its default. The only hand-written parts are the header and the
compose credentials, which are read by compose rather than by the application and so
belong to no field. `test_env_example.py` fails if the committed file and this
renderer disagree, which is the part that makes it a safeguard rather than a habit.
"""

from __future__ import annotations

import textwrap
from pathlib import Path
from typing import Any

from floodline.settings import Settings

__all__ = ["ENV_EXAMPLE", "render_env_example"]

ENV_EXAMPLE = Path(__file__).resolve().parents[2] / ".env.example"

_WIDTH = 76

_HEADER = """\
# floodline deployment settings.
#
# GENERATED by `floodline env-template --write`. Do not edit by hand: the
# descriptions and defaults below come from `floodline.settings.Settings`, and
# a test fails if this file and that model disagree. To change a comment here,
# change the field's description there.
#
# Copy to .env and set what your deployment needs. Almost every value below is
# the default, so you only need lines for what you are actually overriding.
#
# The exception is the compose credentials block immediately below. Those have
# no defaults on purpose: `docker compose up` fails naming the missing variable
# rather than starting a database on a password published in a git repository.
#
# Model parameters are NOT here. Manning's roughness, accumulation thresholds,
# curve families and the rest describe what the model is rather than where it
# runs, so they live in core/config.py and are versioned with the code that
# reads them. Changing one changes the answer; changing a setting below does not.

# --------------------------------------------------------------------------
# Compose credentials - REQUIRED, no defaults
# --------------------------------------------------------------------------
# Read by compose, not by the application: they initialise the db service and
# are interpolated into the API's FLOODLINE_DATABASE_URL. Generate the password
# rather than typing one, e.g. `openssl rand -base64 24`.
#
# POSTGRES_PASSWORD initialises a *new* data directory and nothing else. Changing
# it here does not change the password of a database that already exists - the
# api then fails authentication against a db that is otherwise healthy. To rotate
# it on a running stack, ALTER the role; to start over, `docker compose down -v`,
# which deletes the data.
POSTGRES_USER=floodline
POSTGRES_PASSWORD=
POSTGRES_DB=floodline

# --------------------------------------------------------------------------
# Compose: the public address
# --------------------------------------------------------------------------
# Unprefixed, like POSTGRES_*, because the FLOODLINE_ prefix belongs to the
# application's settings model: anything carrying it should be a field on
# `floodline.settings.Settings`, and a test enforces that. These are read by
# compose.
#
# The hostname Caddy serves and gets a Let's Encrypt certificate for. It must
# already resolve to this machine, and ports 80 and 443 must reach it, before
# the first request - that is how the certificate is issued.
#
# Left unset this is `localhost`, served from Caddy's own internal CA: right
# for a check on the machine itself, and a browser warning anywhere else.
PUBLIC_DOMAIN=
# Where Let's Encrypt sends expiry warnings if renewal ever stops working.
ACME_EMAIL=
# Set to 1 to rehearse against Let's Encrypt's staging CA on a new domain. Same
# failure modes, no meaningful rate limit, and the certificate it issues is
# untrusted - which is what you want from a rehearsal. Unset it and restart the
# proxy once a staging certificate has been issued.
ACME_STAGING=
"""


def _comment(text: str) -> list[str]:
    """Wrap prose to the file's width, as comment lines."""
    return [f"# {line}" for line in textwrap.wrap(text, width=_WIDTH)]


def _value(default: Any) -> str:
    """Render a default the way an operator would type it into a shell."""
    if isinstance(default, Path):
        return str(default)
    if isinstance(default, bool):
        return "true" if default else "false"
    return str(default)


def render_env_example() -> str:
    """Return the full text of `.env.example` for the current settings model."""
    lines = [_HEADER.rstrip("\n")]

    for name, field in Settings.model_fields.items():
        # `json_schema_extra` may also be a callable that mutates the schema; only
        # the mapping form carries a section marker.
        extra = field.json_schema_extra
        marker = extra.get("section") if isinstance(extra, dict) else None
        if isinstance(marker, dict):
            lines += [
                "",
                "",
                "# " + "-" * 74,
                f"# {marker['title']}",
                "# " + "-" * 74,
            ]
            note = str(marker.get("note") or "")
            if note:
                lines += _comment(note)
        else:
            lines.append("")

        if field.description:
            lines += _comment(field.description)
        lines.append(f"FLOODLINE_{name.upper()}={_value(field.default)}")

    return "\n".join(lines) + "\n"
