"""basin cache, buildings and admin units

Revision ID: e17b0c5fff06
Revises:
Create Date: 2026-09-07 13:01:56.427486

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e17b0c5fff06"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerate inspects tables, not extensions, so it cannot know the geometry
    # columns below need PostGIS present. Creating it here means a fresh database is
    # migrated in one step rather than in one step plus a README instruction.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_units",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("area_km2", sa.Float(), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "code", name="uq_admin_units_kind_code"),
    )
    op.create_index(
        "ix_admin_units_geom", "admin_units", ["geom"], unique=False, postgresql_using="gist"
    )
    op.create_index(op.f("ix_admin_units_kind"), "admin_units", ["kind"], unique=False)
    op.create_table(
        "basin_cache",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("huc", sa.String(length=16), nullable=False),
        sa.Column("params_hash", sa.String(length=64), nullable=False),
        sa.Column("resolution_m", sa.Float(), nullable=False),
        sa.Column("crs", sa.String(length=64), nullable=False),
        sa.Column("cell_count", sa.BigInteger(), nullable=False),
        sa.Column("stream_cells", sa.Integer(), nullable=False),
        sa.Column("reach_count", sa.Integer(), nullable=False),
        sa.Column("compute_seconds", sa.Float(), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("use_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("huc", "params_hash", name="uq_basin_cache_huc_params"),
    )
    op.create_index("ix_basin_cache_last_used", "basin_cache", ["last_used_at"], unique=False)
    op.create_table(
        "buildings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("fd_id", sa.String(length=32), nullable=False),
        sa.Column("huc", sa.String(length=16), nullable=False),
        sa.Column("cbfips", sa.String(length=15), nullable=True),
        sa.Column("occtype", sa.String(length=32), nullable=True),
        sa.Column("val_struct", sa.Float(), nullable=True),
        sa.Column("val_cont", sa.Float(), nullable=True),
        sa.Column("sqft", sa.Float(), nullable=True),
        sa.Column("num_story", sa.Float(), nullable=True),
        sa.Column("found_ht", sa.Float(), nullable=True),
        sa.Column("pop_night", sa.Float(), nullable=True),
        sa.Column("pop_day", sa.Float(), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fd_id", "huc", name="uq_buildings_fd_huc"),
    )
    op.create_index(op.f("ix_buildings_fd_id"), "buildings", ["fd_id"], unique=False)
    op.create_index(
        "ix_buildings_geom", "buildings", ["geom"], unique=False, postgresql_using="gist"
    )
    op.create_index(op.f("ix_buildings_huc"), "buildings", ["huc"], unique=False)
    op.create_index(op.f("ix_buildings_occtype"), "buildings", ["occtype"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # The extension is deliberately not dropped: another schema in the same database
    # may be using it, and dropping it would take their geometry columns with it.
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_buildings_occtype"), table_name="buildings")
    op.drop_index(op.f("ix_buildings_huc"), table_name="buildings")
    op.drop_index("ix_buildings_geom", table_name="buildings", postgresql_using="gist")
    op.drop_index(op.f("ix_buildings_fd_id"), table_name="buildings")
    op.drop_table("buildings")
    op.drop_index("ix_basin_cache_last_used", table_name="basin_cache")
    op.drop_table("basin_cache")
    op.drop_index(op.f("ix_admin_units_kind"), table_name="admin_units")
    op.drop_index("ix_admin_units_geom", table_name="admin_units", postgresql_using="gist")
    op.drop_table("admin_units")
    # ### end Alembic commands ###
